apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "developer" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ include "generic-chart.fullname" . }}
  {{- with .Values.clusterRoleBinding.subjects}}
subjects:
  {{- toYaml | nindent 2 -}}
  apiGroup: rbac.authorization.k8s.io
  {{- end}}
roleRef:
  kind: ClusterRole
  name: {{ include "generic-chart.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
