apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "generic-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
spec:
  {{- if .values.job.parallelism }}
  parallelism: {{ .Values.job.parallelism }}
  selector:
    matchLabels:
      {{- include "generic-chart.selectorLabels" . | nindent 6 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.job.Annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{ - include "generic-chart.labels" . | nindent 8 }}
        {{ - with .Values.podLabels }}
        {{ - toYaml . | nindent 8 }}
        {{ - end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "generic-chart.serviceAccountName" .}}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "generic-chart.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.job.image.pullPolicy }}
          command: [ "python", "-c" ]
          args: [ "print('Hello from the Kubernetes job')" ]
          {{- with .Values.job.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{ - with .Values.job.readinessProbe }}
          readinessProbe:
            {{ - toYaml . | nindent 12 }}
          {{ - end }}
          {{ - with .Values.job.volumeMounts }}
          volumeMounts:
            {{ - toYaml . | nindent 12 }}
          {{ - end }}
      {{- with .Values.job.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .values.job.restartPolicy }}
  backoffLimit: 4
  