apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - cronjob.yaml
  - daemonset.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml
  - job.yaml
  - poddisruptionbudget.yaml
  - priorityclass.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml