apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "generic-chart.fullname" . }}
{{- with .Values.roleBinding.subjects}}
subjects:
  {{- toYaml | nindent 2 -}}
    apiGroup: rbac.authorization.k8s.io
{{- end}}
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: {{ include "generic-chart.fullname" . }} # must match the name of the Role
  apiGroup: rbac.authorization.k8s.io